ALTER TABLE authors
ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMPTZ,
ADD COLUMN created_by BIGINT NOT NULL,
ADD COLUMN updated_by BIGINT;

ALTER TABLE novels
ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMPTZ,
ADD COLUMN created_by BIGINT NOT NULL,
ADD COLUMN updated_by BIGINT;